[tool.poetry]
name = "quranbot-admin"
version = "0.1.0"
description = ""
authors = ["Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.79.0"
uvicorn = "^0.18.2"
requests = "^2.28.1"
asyncpg = "^0.25.0"
pydantic = {extras = ["dotenv"], version = "^1.9.1"}

[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.16.1"
ipython = "^8.4.0"
mypy = "^0.961"
asyncpg-stubs = "^0.25.4"
Faker = "^13.14.0"
pytest-cov = "^3.0.0"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
