[tool.poetry]
name = "quranbot-admin"
version = "0.1.0"
description = ""
authors = ["Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.86.0"
uvicorn = "^0.18.2"
requests = "^2.28.1"
pydantic = {extras = ["dotenv"], version = "^1.9.1"}
loguru = "^0.6.0"
PyPika = "^0.48.9"
nats-py = "^2.1.4"
bcrypt = "^3.2.2"
passlib = "^1.7.4"
python-jose = "^3.3.0"
python-multipart = "^0.0.5"
quranbot-schema-registry = { git= "https://github.com/blablatdinov/quranbot-schema-registry", branch = "master" }
aioredis = "^2.0.1"
websockets = "^10.3"
Jinja2 = "^3.1.2"  # remove after writing ui
databases = {extras = ["asyncpg"], version = "^0.6.0"}
aiofiles = "^0.8.0"
alembic = "^1.8.1"
SQLAlchemy = "^1.4.40"

[tool.poetry.dev-dependencies]
wemake-python-styleguide = { git= "https://github.com/wemake-services/wemake-python-styleguide", branch = "master" }
ipython = "^8.4.0"
mypy = "^0.991"
asyncpg-stubs = "^0.26.0"
Faker = "^13.14.0"
pytest-cov = "^3.0.0"
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"
types-aiofiles = "^0.8.10"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
