[tool.poetry]
name = "quranbot-admin"
version = "0.1.0"
description = ""
authors = ["Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
fastapi = "0.95.2"
uvicorn = "0.22.0"
pydantic = {extras = ["dotenv"], version = "^1.9.1"}
loguru = "0.7.0"
PyPika = "0.48.9"
nats-py = "2.2.0"
bcrypt = "4.0.1"
passlib = "1.7.4"
python-jose = "3.3.0"
python-multipart = "0.0.6"
quranbot-schema-registry = { git= "https://github.com/blablatdinov/quranbot-schema-registry", branch = "master" }
aioredis = "2.0.1"
websockets = "10.4"
Jinja2 = "3.1.2"  # remove after writing ui
databases = {extras = ["asyncpg"], version = "^0.7.0"}
aiofiles = "22.1.0"
alembic = "1.11.0"
SQLAlchemy = "1.4.48"
httpx = "0.24.0"

[tool.poetry.dev-dependencies]
wemake-python-styleguide = { git= "https://github.com/wemake-services/wemake-python-styleguide", branch = "master" }
ipython = "8.13.2"
mypy = "0.991"
asyncpg-stubs = "0.27.0"
Faker = "15.3.4"
pytest-cov = "4.0.0"
pytest = "7.3.1"
pytest-asyncio = "0.21.0"
types-aiofiles = "22.1.0.9"
black = "22.12.0"
requests = "2.30.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
