# Generated by Django 4.2.10 on 2024-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayat',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
