# Generated by Django 4.2.10 on 2024-03-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_callbackdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='trigger_callback_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
