# Generated by Django 4.2.10 on 2024-02-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_alter_ayat_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayat',
            name='public_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
