# Generated by Django 4.2.10 on 2024-02-20 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_alter_ayat_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referrer_id',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
