# Generated by Django 4.2.10 on 2024-03-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mailing_message_user_message_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.mailing'),
        ),
    ]
