---

# This compose-file is production only. So, it should not be called directly.
#
# Instead, it should be a part of your deployment strategy.
# This setup is supposed to be used with `docker-swarm`.
# See `./docs/pages/template/production.rst` docs.

version: "3.8"
services:
  web:
    # Image for production:
    image: "blablatdinov/quranbot-admin:latest"
    restart: always
    env_file: ../config/.env
    volumes:
      - django-media:/var/www/django/media  # since in dev it is app's folder
      - django-locale:/code/locale  # since in dev it is app's folder
    command: |
      /usr/local/bin/gunicorn --config python:docker.django.gunicorn_config server.wsgi
    ports:
      - "8010:8010"

  receive_events:
    image: "blablatdinov/quranbot-admin:latest"
    restart: always
    env_file: ../config/.env
    command: |
      /usr/local/bin/python manage.py receive_events

# This task is an example of how to extend existing ones:
#   some_worker:
#     <<: *web
#     command: python manage.py worker_process
#     deploy:
#       replicas: 2

volumes:
  django-media:
  django-locale:
